function t179_showvideo(recid){$("#rec"+recid+" .t179__playbutton").css("display","none");$("#rec"+recid+" .t179__videocontainer").css("display","block");var height=$("#rec"+recid+" .t179__videocontainer").attr("data-height");var youtubeid=$("#rec"+recid+" .t179__videocontainer").attr("data-youtube-id");if(height=="")height="540";$("#youtubeiframe_carier"+recid).html("<iframe id=\"youtubeiframe{$a.id}\" width=\"100%\" height=\""+height+"\" src=\"//www.youtube.com/embed/"+youtubeid+(youtubeid.indexOf('?')!==-1?'&':'?')+"autoplay=1&rel=0&fmt=18\" frameborder=\"0\" allowfullscreen></iframe>");if(height==""){var div=$("#youtubeiframe"+recid);var height=div.width()*0.5625;div.css("height",height)}}
function t570_init(recid){if($(window).width()>750){t570_setMapHeight(recid);$(window).on('load',function(){t570_setMapHeight(recid)});$(window).on('resize',function(){t570_setMapHeight(recid)})}}
function t570_setMapHeight(recid){var t570__el=$('#rec'+recid),t570__map=t570__el.find('.t-map');var t570__textwrapper=t570__el.find('.t570__col_text').height();t570__map.css('height',t570__textwrapper).trigger('sizechange')}
function t678_onSuccess(t678_form){var t678_inputsWrapper=t678_form.find('.t-form__inputsbox');var t678_inputsHeight=t678_inputsWrapper.height();var t678_inputsOffset=t678_inputsWrapper.offset().top;var t678_inputsBottom=t678_inputsHeight+t678_inputsOffset;var t678_targetOffset=t678_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t678_target=t678_targetOffset-200}else{var t678_target=t678_targetOffset-100}
if(t678_targetOffset>$(window).scrollTop()||($(document).height()-t678_inputsBottom)<($(window).height()-100)){t678_inputsWrapper.addClass('t678__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t678_target},400);setTimeout(function(){t678_inputsWrapper.addClass('t678__inputsbox_hidden')},400)}
var successurl=t678_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t829_init(recid){var rec=$('#rec'+recid);var grid=rec.find('.t829__grid');var sizer=rec.find('.t829__grid-sizer');var item=rec.find('.t829__grid-item');var images=rec.find('.t829__grid img');var startContainerWidth=rec.find('.t829__grid-sizer').width();images.load(function(){if(!(grid.hasClass('t829__container_mobile-flex')&&$(window).width()<768)&&rec.is(':visible')){t829_initMasonry(rec,recid,grid)}});if(!(grid.hasClass('t829__container_mobile-flex')&&$(window).width()<768)&&rec.is(':visible')){t829_initMasonry(rec,recid,grid);t829_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)}
grid.bind('touchmove scroll',function(){if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}});$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&window.isMobile){return}
if(!(grid.hasClass('t829__container_mobile-flex'))){t829_initMasonry(rec,recid,grid)}
if(grid.hasClass('t829__container_mobile-flex')&&$(window).width()>=768){t829_initMasonry(rec,recid,grid)}
if(!(grid.hasClass('t829__container_mobile-flex')&&$(window).width()<768)){t829_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)}}));rec.find('.t829').bind('displayChanged',function(){if(!(grid.hasClass('t829__container_mobile-flex'))){t829_initMasonry(rec,recid,grid)}
if(grid.hasClass('t829__container_mobile-flex')&&$(window).width()>=768){t829_initMasonry(rec,recid,grid)}
if(!(grid.hasClass('t829__container_mobile-flex')&&$(window).width()<768)){t829_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)}})}
function t829_initMasonry(rec,recid,grid){var $grid=grid;var gutterSizerWidth=rec.find('.t829__gutter-sizer').width();var gutterElement=rec.find('.t829__gutter-sizer').width()==40?39:'#rec'+recid+' .t829__gutter-sizer';t_onFuncLoad('imagesLoaded',function(){$grid.imagesLoaded(function(){$grid.masonry({itemSelector:'#rec'+recid+' .t829__grid-item',columnWidth:'#rec'+recid+' .t829__grid-sizer',gutter:gutterElement,isFitWidth:!0,transitionDuration:0})})})}
function t829_calcColumnWidth(rec,startcontainerwidth,grid,sizer,item){var containerWidth=rec.find('.t829__container').width();var sizerWidth=rec.find('.t829__grid-sizer').width();var itemWidth=rec.find('.t829__grid-item').width();var gutterSizerWidth=rec.find('.t829__gutter-sizer').width()==40?39:rec.find('.t829__gutter-sizer').width();var columnAmount=Math.round(containerWidth/startcontainerwidth);var newSizerWidth=((containerWidth-gutterSizerWidth*(columnAmount-1))/columnAmount);newSizerWidth=Math.floor(newSizerWidth);if(containerWidth>=itemWidth){sizer.css('width',newSizerWidth);item.css('width',newSizerWidth)}else{grid.css('width','100%');sizer.css('width','100%');item.css('width','100%')}}
function t905_init(recid){var el=$('#rec'+recid);t905_unifyHeights(recid);$(window).on('resize',t_throttle(function(){t905_unifyHeights(recid)}));$(window).on('load',function(){t905_unifyHeights(recid)});el.find('.t905').on('displayChanged',function(){t905_unifyHeights(recid)})}
function t905_unifyHeights(recid){var el=$('#rec'+recid);var cards=el.find('.t905__card');cards.each(function(i,card){var img=$(card).find('.t905__image');var imgHeight=$(img).outerHeight();var content=$(card).find('.t905__content');var contentHeight=$(content).outerHeight();if(contentHeight>imgHeight){img.css('height',contentHeight+'px');img.css('padding-bottom','initial')}})}